spring:
  datasource:
    driver-class-name: org.h2.Driver
#    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2

mybatis:
  mapper-locations: mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: me.potato.demomybatisjsoncolumn.entities
  type-handlers-package: me.potato.demomybatisjsoncolumn.typehandlers